[package]
authors = ["HowManySmall <howmanysmall@gmail.com>", "Validark <Validark@pm.me>"]
description = "A collection of data structures aimed specifically at Roblox game development."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
license = "MIT"
name = "howmanysmall/bura-data-structures"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.1.0"

[dependencies]
Error = "howmanysmall/error@1.1.0"
GreenTea = "corecii/greentea@0.4.11"
GreenTeaUtilities = "howmanysmall/greentea-utilities@1.6.0"

[dev-dependencies]
Jest = "jsdotlua/jest@3.6.1-rc.2"
JestGlobals = "jsdotlua/jest-globals@3.6.1-rc.2"
